# Generated by Django 4.1.5 on 2023-02-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome', 'funcao']},
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
    ]
