# Generated by Django 4.1.5 on 2023-02-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_options_pessoa_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Cadastro Ativo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('PA', 'Paciente'), ('ME', 'Médico'), ('FU', 'Funcionário')], default='PA', max_length=2, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='Data de Nascimento'),
        ),
    ]
